version: '3.4'

services:
  desafio.ca.crud.api:
    image: desafiocacrudapi
    build:
      context: ../src/
      dockerfile: Desafio.Ca.Crud.Api/Dockerfile
    ports:
      - 8080:80
    depends_on:
        - db
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"